# Generated by Django 4.0.2 on 2022-02-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contactmail',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cellphone',
            field=models.PositiveIntegerField(),
        ),
    ]
